name: yanzu_app
description: A rental house application.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_swiper_view: ^1.1.8
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.5
  audioplayers: ^5.2.1
  share_plus: ^7.2.2
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 